name: Health Metrics

on: [push, pull_request]

env:
  GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
  # TODO(yifany): parse from git commit history directly
  #   Reason: actions/checkout@v2 does not always honor ${{ github.event.pull_request.base.sha }},
  #           therefore "base.sha" sometimes is not the commit that actually gets merged with the
  #           pull request head commit for CI test.
  #   See:
  #     - https://github.com/actions/checkout/issues/27
  #     - https://github.com/actions/checkout/issues/237
  GITHUB_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  binary-size:
    name: Binary Size
    if: github.event_name == 'push' || !(github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: yarn install
      - run: yarn build
      - name: Run health-metrics/binary-size test
        run: yarn size-report
  modular-export-size:
    name: Binary Size For Modular Exports
    if: github.event_name == 'push' || !(github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: yarn install
      - run: yarn build
      - name: Run health-metrics/modular-exports-binary-size test
        run: yarn modular-export-size-report
  # TODO(yifany): Enable startup times testing on CI.
