name: Health Metrics

on: [push, pull_request]

jobs:
  binary-size-test:
    name: Binary Size
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != 'true'
    runs-on: ubuntu-latest
    env:
      METRICS_SERVICE_URL: ${{ secrets.METRICS_SERVICE_URL }}
      GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event.pull_request.head.repo.fork }}"
          echo "${{ github.event_name != 'pull_request' }}"
          echo "${{ github.event.pull_request.head.repo.fork != 'true' }}"
          echo "${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork != 'true' }}"
          echo "${{ (github.event_name != 'pull_request') || (github.event.pull_request.head.repo.fork != 'true') }}"

  # TODO(yifany): Enable startup times testing on CI.
