name: Merge Release Into Master

on: workflow_dispatch

jobs:
  merge_to_master:
    runs-on: ubuntu-latest
    # Allow GITHUB_TOKEN to have write permissions
    permissions:
      contents: write
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@master
        with:
          ref: release
      - name: Get release version
        id: get-version
        run: |
          export VERSION_SCRIPT="const pkg = require('./packages/firebase/package.json'); console.log(pkg.version);"
          export VERSION=`node -e "${VERSION_SCRIPT}"`
          echo "::set-output name=RELEASE_VERSION::$VERSION"
      - name: Echo version in shell
        run: |
          echo "Merging release ${STEPS_GET_VERSION_OUTPUTS_RELEASE_VERSION}"
        env:
          STEPS_GET_VERSION_OUTPUTS_RELEASE_VERSION: ${{ steps.get-version.outputs.RELEASE_VERSION }}
      - name: Merge to master
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'master',
              head: 'release',
              commit_message: 'Release ${{ steps.get-version.outputs.RELEASE_VERSION }}'
            })
