name: Update API reports

on: pull_request

jobs:
  update_api_reports:
    name: Update API reports
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        # checkout HEAD commit instead of merge commit
        ref: ${{ github.event.pull_request.head.sha }}
        token: ${{ github.token }}
    - name: Set up Node (14)
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Yarn install
      run: yarn
    - name: Update API reports
      # API reports are generated as part of the build
      run: yarn build
      id: update-api-reports
    - name: Commit & Push changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'common/api-review/*'
        message: 'Update API reports'
        default_author: github_actor